### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by abahadirdogan** [kaeluka/atom-haskell-hoogle#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Ubuntu 12.04.5
**Thrown From**: [haskell-hoogle](https://github.com/kaeluka/atom-haskell-hoogle) package, v0.1.2
### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/destek/.atom/packages/haskell-hoogle/lib/haskell-hoogle.coffee:10

TypeError: undefined is not a function
  at Object.module.exports.HaskellHoogle.getSearchText (/home/destek/.atom/packages/haskell-hoogle/lib/haskell-hoogle.coffee:10:19)
  at Object.module.exports.HaskellHoogle.lookup (/home/destek/.atom/packages/haskell-hoogle/lib/haskell-hoogle.coffee:13:13)
  at atom-workspace.<anonymous> (/home/destek/.atom/packages/haskell-hoogle/lib/haskell-hoogle.coffee:6:70)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:241:29)
  at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:156:19)
  at EventEmitter.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```
### Commands

```
     -7:13.7.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -7:09.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -7:08.2.0 editor:select-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
     -7:08.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -7:01.4.0 core:paste (atom-text-editor.editor.mini.is-focused)
  4x -6:33.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -5:20.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:32.8.0 application:open (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:00.4.0 haskell-hoogle:lookup (button.btn.btn-primary)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
autocomplete-haskell, v0.4.5
haskell-ghc-mod, v0.8.12
haskell-grammar, v0.4.0
haskell-hoogle, v0.1.2
haskell-pointfree, v0.1.2
hover-tooltips-hdevtools, v0.5.0
ide-haskell, v0.7.1
language-haskell, v1.3.1
linter-hdevtools, v1.4.0
linter-hlint, v0.4.2

# Dev
No dev packages
```

**Comment by kaeluka** [comment]
What did you do to get this bug?
